config/urls.py
from django.contrib import admin
from django.urls import path,include
from core.homepage.views import indexView
from core.login.views import loginFormView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('erp/', include('core.erp.urls')),
    path('login/', include('core.login.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/erp/urls.py
from django.urls import path
from core.erp.views.category.views import *
from core.erp.views.cargo.views import *
from core.erp.views.regional.views import *
from core.erp.views.centro.views import *
from core.erp.views.formacion.views import *
from core.erp.views.aprendiz.views import *
from core.erp.views.funcionario.views import *
from core.erp.views.logo.views import *

app_name = 'erp'

urlpatterns = [
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    path('cargo/list/', CargoListView.as_view(), name='cargo_list'),
    path('cargo/add/', CargoCreateView.as_view(), name='cargo_create'),
    path('cargo/update/<int:pk>/', CargoUpdateView.as_view(), name='cargo_update'),
    path('cargo/delete/<int:pk>/', CargoDeleteView.as_view(), name='cargo_delete'),
    path('regional/list/', regionalListView.as_view(), name='regional_list'),
    path('regional/add/', RegionalCreateView.as_view(), name='regional_create'),
    path('regional/update/<int:pk>/', RegionalUpdateView.as_view(), name='regional_update'),
    path('regional/delete/<int:pk>/', RegionalDeleteView.as_view(), name='regioanl_delete'),
    path('centro/list/', centroListView.as_view(), name='centro_list'),
    path('centro/add/', centroCreateView.as_view(), name='centro_create'),
    path('centro/update/<int:pk>/', centroUpdateView.as_view(), name='centro_update'),
    path('centro/delete/<int:pk>/', CentroDeleteView.as_view(), name='centro_delete'),
    path('formacion/list/', formacionListView.as_view(), name='formacion_list'),
    path('formacion/add/', formacionCreateView.as_view(), name='formacion_create'),
    path('formacion/update/<int:pk>/', formacionUpdateView.as_view(), name='formacion_update'),
    path('formacion/delete/<int:pk>/', formacionDeleteView.as_view(), name='formacion_delete'),

    path('aprendiz/generar/<int:pk>/', generar_carnet_pdf, name='aprendiz_generar'),
    path('aprendiz/list/', AprendizListView.as_view(), name='aprendiz_list'),
    path('aprendiz/add/', AprendizCreateView.as_view(), name='aprendiz_create'),
    path('aprendiz/update/<int:pk>/', AprendizupdateView.as_view(), name='aprendiz_update'),
    path('aprendiz/delete/<int:pk>/', AprendizDeleteView.as_view(), name='aprendiz_delete'),
    path('funcionario/list/', funcionarioListView.as_view(), name='funcionario_list'),
    path('funcionario/add/', funcionarioCreateView.as_view(), name='funcionario_create'),
    path('funcionario/update/<int:pk>/', funcionarioupdateView.as_view(), name='funcionario_update'),
    path('funcionario/delete/<int:pk>/', funcionarioDeleteView.as_view(), name='funcionario_delete'),
    path('logo/list/', LogoListView.as_view(), name='logo_list'),
    path('logo/add/', LogoCreateView.as_view(), name='logo_create'),
    path('logo/update/<int:pk>/', LogoUpdateView.as_view(), name='logo_update'),
    path('logo/delete/<int:pk>/', LogoDeleteView.as_view(), name='logo_delete'),
]

core/erp/views/aprendiz/views.py
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import *
from django.http import HttpResponseRedirect

from django.shortcuts import render
from django.http import HttpResponse

from core.erp.forms import AprendizForm
from core.erp.models import Aprendiz,logo


def generar_carnet_pdf(request,pk):
    datos = Aprendiz.objects.filter(pk=pk)
    imglogo = logo.objects.all()

    return render(request, 'aprendiz/generar.html',{'datos': datos,'imglogo': imglogo})


class AprendizListView(ListView):
    model = Aprendiz
    template_name = 'aprendiz/list.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Aprendiz.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        print(data)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Aprendices'
        context['create_url'] = reverse_lazy('erp:aprendiz_create')
        context['list_url'] = reverse_lazy('erp:aprendiz_list')
        context['entity'] = 'Aprendiz'
        return context

class AprendizCreateView(CreateView):
    model = Aprendiz
    form_class = AprendizForm
    template_name = 'aprendiz/create.html'
    success_url = reverse_lazy('erp:aprendiz_list')

    def form_valid(self, form):

        
        self.object = form.save()
        return HttpResponseRedirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Creación una Aprendiz'
        context['entity'] = 'Aprendiz'
        context['list_url'] = reverse_lazy('erp:aprendiz_list')
        context['action'] = 'add'
        return context
    

class AprendizupdateView(UpdateView):
    model = Aprendiz
    form_class = AprendizForm
    template_name = 'aprendiz/create.html'
    success_url = reverse_lazy('erp:aprendiz_list')

    def form_valid(self, form):
        self.object = form.save()
        return HttpResponseRedirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edición una Aprendiz'
        context['entity'] = 'Aprendiz'
        context['list_url'] = reverse_lazy('erp:aprendiz_list')
        context['action'] = 'edit'
        return context


class AprendizDeleteView(DeleteView):
    model = Aprendiz
    template_name = 'aprendiz/delete.html'
    success_url = reverse_lazy('erp:aprendiz_list')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminación de una Aprendiz'
        context['entity'] = 'Centros'
        context['list_url'] = reverse_lazy('erp:aprendiz_list')
        return context

core/erp/views/cargo/views.py
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import *

from core.erp.forms import CargoForm
from core.erp.models import Cargo

class CargoListView(ListView):
    model = Cargo
    template_name = 'cargo/list.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Cargo.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Cargos'
        context['create_url'] = reverse_lazy('erp:cargo_create')
        context['list_url'] = reverse_lazy('erp:cargo_list')
        context['entity'] = 'Cargos'
        return context

class CargoCreateView(CreateView):
    model = Cargo
    form_class = CargoForm
    template_name = 'cargo/create.html'
    success_url = reverse_lazy('erp:cargo_list')

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Creación una Cargo'
        context['entity'] = 'Cargo'
        context['list_url'] = reverse_lazy('erp:cargo_list')
        context['action'] = 'add'
        return context
    

class CargoUpdateView(UpdateView):
    model = Cargo
    form_class = CargoForm
    template_name = 'cargo/create.html'
    success_url = reverse_lazy('erp:cargo_list')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edición una Cargo'
        context['entity'] = 'Cargo'
        context['list_url'] = reverse_lazy('erp:cargo_list')
        context['action'] = 'edit'
        return context


class CargoDeleteView(DeleteView):
    model = Cargo
    template_name = 'cargo/delete.html'
    success_url = reverse_lazy('erp:cargo_list')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminación de una Cargo'
        context['entity'] = 'Cargos'
        context['list_url'] = reverse_lazy('erp:cargo_list')
        return context

core/erp/views/category/views.py
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import *

from core.erp.forms import CategoryForm
from core.erp.models import Category


class CategoryListView(ListView):
    model = Category
    template_name = 'category/list.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Category.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Categorías'
        context['create_url'] = reverse_lazy('erp:category_create')
        context['list_url'] = reverse_lazy('erp:category_list')
        context['entity'] = 'Categorias'
        return context


class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'category/create.html'
    success_url = reverse_lazy('erp:category_list')

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Creación una Categoria'
        context['entity'] = 'Categorias'
        context['list_url'] = reverse_lazy('erp:category_list')
        context['action'] = 'add'
        return context


class CategoryUpdateView(UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'category/create.html'
    success_url = reverse_lazy('erp:category_list')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edición una Categoria'
        context['entity'] = 'Categorias'
        context['list_url'] = reverse_lazy('erp:category_list')
        context['action'] = 'edit'
        return context


class CategoryDeleteView(DeleteView):
    model = Category
    template_name = 'category/delete.html'
    success_url = reverse_lazy('erp:category_list')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Eliminación de una Categoria'
        context['entity'] = 'Categorias'
        context['list_url'] = reverse_lazy('erp:category_list')
        return context

core/erp/templates/aprendiz/create.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" action="." enctype="multipart/form-data">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-edit"></i>
                    {% endif %}

                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        {% if field.label == 'id_imgAprendices' %}
                            <img src="{{ field.value.url }}" alt="{{ field.label }}" class="img-fluid" style="width: 200px; height: 200px;">
                        {% endif %}
                        <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                        {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                </div>
                {% endfor %}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>
        {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                errors += '{{ error }}\n';
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}

/*$('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = $(this).serializeArray();
            submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de realizar la siguiente acción?', parameters, function () {
                location.href = '{{ list_url }}';
            });
        });*/
    </script>
{% endblock %}

core/erp/templates/aprendiz/generar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
{% for dato in datos %} 


<img src="{{ imglogo.logoimg.url }}" alt="Logo">

    <div class="container">
        <div class="title">{{dato.cargo}}</div>
        <div class="info-group">

            <img src="{{ dato.imgAprendices.url }}" alt="foto">

           


            <div class="info-label">Nombre:</div>
            <div class="info-value">{{dato.names}}</div>
        </div>
        <div class="info-group">
            <div class="info-label">Apellidos:</div>
            <div class="info-value">{{dato.surnames}}</div>
        </div>
        <div class="info-group">
            <div class="info-label">{{dato.tipoDocumento}}</div>
            <div class="info-value">{{dato.numeroDocumento}}</div>
        </div>
        <div class="info-group">
            <div class="info-label">Tipo de Sangre:</div>
            <div class="info-value">{{dato.tipoSangre}}</div>
        </div>
        <div class="info-group">
            <div class="info-label">Fecha de Nacimiento:</div>
            <div class="info-value">1993-05-18</div>
        </div>
        <div class="info-group">
            <div class="info-label">Regional Santander<div>
            <div class="info-value">Centro Agroempresaril y turisticoandes</div>
        </div>


    </div>

    {% endfor %}
</body>
</html>

core/erp/templates/aprendiz/list.html
{% extends 'list.html' %}
{% load static %}
{% block columns %}
    <tr>
        <th scope="col" style="width: 10%;">Nro</th>
        <th scope="col" style="width: 20%;">Nombre</th>
        <th scope="col" style="width: 20%;">Apellido</th>
        <th scope="col" style="width: 20%;">Cargo</th>
        <th scope="col" style="width: 20%;">Tipo Documento</th>
        <th scope="col" style="width: 20%;">Numero Documento</th>
        <th scope="col" style="width: 20%;">Tipo Sangre</th>
        <th scope="col" style="width: 20%;">Formacion</th>
        <th scope="col" style="width: 20%;">Foto</th>
        <th scope="col" style="width: 20%;">Generar Carnet</th>
        <th scope="col" style="width: 20%;">Opciones</th>
    </tr>
{% endblock %}

{% block rows %}
    {% for obj in object_list %}
        <tr>
            <td>{{ obj.id }}</td>
            <td>{{ obj.cargo}}</td>
            <td>{{ obj.names }}</td>
            <td>{{ obj.surnames }}</td>
            <td>{{ obj.tipoDocumento }}</td>
            <td>{{ obj.numeroDocumento}}</td>
            <td>{{ obj.tipoSangre }}</td>
            <td>{{ obj.Formacion }}</td>
            <td class="text-center">
                <img src="/media/{{ obj.imgAprendices}}" class="img-fluid d-block mx-auto" style="width: 50px; height: 50px;">
            </td>

            <td class="text-center">
                <a href="{% url 'erp:aprendiz_generar' obj.id %}" class="btn btn-warning">
                    Generar Carnet
                </a>
            </td>

            <td class="text-center">
                <a href="{% url 'erp:aprendiz_update' obj.id %}" class="btn btn-warning btn-xs btn-flat">
                    <i class="fas fa-edit"></i>
                </a>
                <a href="{% url 'erp:aprendiz_delete' obj.id %}" class="btn btn-danger btn-xs btn-flat">
                    <i class="fas fa-trash"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}